# Generated by Django 4.2.1 on 2023-05-18 08:44

from django.db import migrations, models
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=70)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
