# Generated by Django 4.2.1 on 2023-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_firstname_menu_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='lastName',
            new_name='lName',
        ),
    ]
