# Generated by Django 4.2.1 on 2023-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_lastname_menu_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=60)),
                ('last_Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
