# Generated by Django 4.2.1 on 2023-05-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_menutemplates'),
    ]

    operations = [
    ]
