# Generated by Django 4.2.1 on 2023-05-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230520_0832'),
    ]

    operations = [
    ]
