# Generated by Django 4.2.1 on 2023-05-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230520_0834'),
    ]

    operations = [
    ]
