# Generated by Django 4.2.1 on 2023-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230520_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('time_log', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
