# Generated by Django 4.2.1 on 2023-05-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='time_log',
            new_name='booking_time',
        ),
    ]
